[project]
name = "server-py"
version = "0.1.0"
description = "Server for testing workflows"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
   "llama-index>=0.14.5",
   "llama-index-workflows[server]>=2.8.0",
]
